### ISSUE TITLE
version cannot be both static and dynamic

### ISSUE THREAD

**Issue by pawamoy** [15r10nk/canonical-imports#2]
The Insiders version defines `version` both as a static field (`version = "0.2.1"`) and a dynamic field (`dynamic = ["version"]` and `[tool.hatch.version] path = "src/canonical_imports/__init__.py"`), which is forbidden by the relevant PEP.

Therefore, trying to build a source distribution fails:

```console
% pyproject-build   
* Creating venv isolated environment...
* Installing packages in isolated environment... (hatchling)
* Getting build dependencies for sdist...
* Building sdist...
Traceback (most recent call last):
  File "/home/pawamoy/.local/pipx/venvs/build/lib/python3.11/site-packages/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
    main()
  File "/home/pawamoy/.local/pipx/venvs/build/lib/python3.11/site-packages/pyproject_hooks/_in_process/_in_process.py", line 335, in main
    json_out['return_val'] = hook(**hook_input['kwargs'])
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pawamoy/.local/pipx/venvs/build/lib/python3.11/site-packages/pyproject_hooks/_in_process/_in_process.py", line 304, in build_sdist
    return backend.build_sdist(sdist_directory, config_settings)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/build-env-g0wj7zqz/lib/python3.11/site-packages/hatchling/build.py", line 34, in build_sdist
    return os.path.basename(next(builder.build(directory=sdist_directory, versions=['standard'])))
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/build-env-g0wj7zqz/lib/python3.11/site-packages/hatchling/builders/plugin/interface.py", line 90, in build
    self.metadata.validate_fields()
  File "/tmp/build-env-g0wj7zqz/lib/python3.11/site-packages/hatchling/metadata/core.py", line 243, in validate_fields
    _ = self.version
        ^^^^^^^^^^^^
  File "/tmp/build-env-g0wj7zqz/lib/python3.11/site-packages/hatchling/metadata/core.py", line 128, in version
    self._version = self._get_version()
                    ^^^^^^^^^^^^^^^^^^^
  File "/tmp/build-env-g0wj7zqz/lib/python3.11/site-packages/hatchling/metadata/core.py", line 224, in _get_version
    version = core_metadata.version
              ^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/build-env-g0wj7zqz/lib/python3.11/site-packages/hatchling/metadata/core.py", line 435, in version
    raise ValueError(message)
ValueError: Metadata field `version` cannot be both statically defined and listed in field `project.dynamic`

ERROR Backend subprocess exited when trying to invoke build_sdist
```

A solution would be to simply remove the `version` static field, since the version is fetched from `__init__.py` dynamically.

**Comment by 15r10nk** [comment]
I removed the dynamic version in 0.3.0
